import { useState } from 'react';
import { Plus, Minus } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
}

const faqData: FAQItem[] = [
  {
    question: "How is this different from just using ChatGPT?",
    answer: "ChatGPT is a blank canvas - you need to know what to ask. Find Your Side is a guided experience designed specifically for side business discovery. We give you a structured questionnaire, generate 5 curated ideas matched to your profile, and deliver a complete 30-day launch plan - all in one place with a clean, saveable format. Think of ChatGPT as raw ingredients, Find Your Side as a complete meal kit with recipe and instructions."
  },
  {
    question: "Is this really personalized or just generic advice?",
    answer: "Every idea and playbook is generated based on YOUR specific skills, available time, interests, and goals. Two people taking the quiz will get completely different ideas. The playbook tasks are also customized - someone with 5 hours/week gets shorter tasks than someone with 15+ hours/week."
  },
  {
    question: "How long does it take?",
    answer: "5 minutes to complete the questionnaire, 30-60 seconds for AI to generate your ideas, another 30 seconds to generate your playbook. Total: It should not take more than 10 minutes from start to downloadable plan."
  },
  {
    question: "Is this really free?",
    answer: "Yes, completely free. No credit card required. You get 5 personalized business ideas and a full 30-day launch playbook at no cost. We may offer premium features in the future (like 60-90 day plans), but the core experience is free."
  },
  {
    question: "What if I don't like the ideas I get?",
    answer: "You can regenerate ideas up to 2 times with the same profile, or retake the quiz with different answers. You may find at least 2-3 ideas that resonate from your first set."
  },
  {
    question: "Do I need business experience to use this?",
    answer: "No! Find Your Side is designed for complete beginners. The playbook assumes you're starting from zero and walks you through every step, starting with validating your idea."
  },
  {
    question: "Can I save and come back to my playbook later?",
    answer: "Yes! We email you a copy of your playbook, and you can download it as a PDF to save locally. You can refer to it anytime."
  },
  {
    question: "Is the AI advice reliable?",
    answer: "Our playbooks are generated by Claude (Anthropic's AI), one of the most advanced AI models available. However, these are suggestions for informational purposes only, not professional business, financial, or legal advice. Always validate ideas with real customers and consult professionals for legal, financial, or tax matters. See our full disclaimer on the home page."
  }
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const toggleQuestion = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const leftColumnFAQs = faqData.slice(0, 4);
  const rightColumnFAQs = faqData.slice(4, 8);

  return (
    <section className="py-20 bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-600">
            Everything you need to know about Find Your Side
          </p>
        </div>

        <div className="grid lg:grid-cols-2 gap-6">
          <div className="space-y-4">
            {leftColumnFAQs.map((faq, index) => (
              <div
                key={index}
                className="border-2 border-gray-200 rounded-lg overflow-hidden transition-all hover:border-gray-300"
              >
                <button
                  onClick={() => toggleQuestion(index)}
                  className="w-full flex items-start justify-between p-5 text-left bg-white hover:bg-gray-50 transition-colors"
                >
                  <span className="text-lg font-bold text-gray-900 pr-4">
                    {faq.question}
                  </span>
                  <span className="flex-shrink-0 mt-1">
                    {openIndex === index ? (
                      <Minus className="w-5 h-5" style={{ color: '#4F46E5' }} />
                    ) : (
                      <Plus className="w-5 h-5" style={{ color: '#4F46E5' }} />
                    )}
                  </span>
                </button>
                <div
                  className={`overflow-hidden transition-all duration-300 ease-in-out ${
                    openIndex === index ? 'max-h-96' : 'max-h-0'
                  }`}
                >
                  <div className="p-5 pt-0 text-gray-700 leading-relaxed">
                    {faq.answer}
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="space-y-4">
            {rightColumnFAQs.map((faq, index) => {
              const actualIndex = index + 4;
              return (
                <div
                  key={actualIndex}
                  className="border-2 border-gray-200 rounded-lg overflow-hidden transition-all hover:border-gray-300"
                >
                  <button
                    onClick={() => toggleQuestion(actualIndex)}
                    className="w-full flex items-start justify-between p-5 text-left bg-white hover:bg-gray-50 transition-colors"
                  >
                    <span className="text-lg font-bold text-gray-900 pr-4">
                      {faq.question}
                    </span>
                    <span className="flex-shrink-0 mt-1">
                      {openIndex === actualIndex ? (
                        <Minus className="w-5 h-5" style={{ color: '#4F46E5' }} />
                      ) : (
                        <Plus className="w-5 h-5" style={{ color: '#4F46E5' }} />
                      )}
                    </span>
                  </button>
                  <div
                    className={`overflow-hidden transition-all duration-300 ease-in-out ${
                      openIndex === actualIndex ? 'max-h-96' : 'max-h-0'
                    }`}
                  >
                    <div className="p-5 pt-0 text-gray-700 leading-relaxed">
                      {faq.answer}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
}
